name: Publish Main

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/**/*.rs"
      - "Cargo.toml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install Rust
        uses: actions-rs/toolchain@v1
        with:
          components: clippy

      - name: clippy lint
        run: cargo lint

      - name: unit test
        run: cargo unit

      - name: unit test ignored
        run: cargo unit-ignored

  publish:
    runs-on: ubuntu-latest
    needs: [unit-tests]
    steps:
      - uses: actions/checkout@v3

      - name: install Rust
        uses: actions-rs/toolchain@v1

      - name: cargo publish
        run: cargo publish
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
